language: php
php:
    - 7.4
    - 7.3
    - 7.2

env:
  - SYMFONY_VERSION="~3.3"
  - SYMFONY_VERSION="~4.0"
  - SYMFONY_VERSION="~4.1"
  - SYMFONY_VERSION="~4.2"
  - SYMFONY_VERSION="~4.3"

before_script:
  - composer selfupdate
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
